INSERT INTO public.customer_types(customer_type_id, customer_type_caption) VALUES (1,'Primary');
INSERT INTO public.customer_types(customer_type_id, customer_type_caption) VALUES (2,'Secondary');
INSERT INTO public.customer_types(customer_type_id, customer_type_caption) VALUES (3,'Royal');
INSERT INTO public.customer_types (customer_type_id, customer_type_caption) VALUES (4, 'Brilliant');
INSERT INTO public.customer_types(customer_type_id, customer_type_caption) VALUES (5,'Nippon');

INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Mary'		, 'Smith'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Patricia'	, 'Johnson'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Linda'		, 'Williams'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Barbara'		, 'Jones'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Elizabeth'	, 'Brown'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Jennifer'	, 'Davis'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Maria'		, 'Miller'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Susan'		, 'Wilson'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Margaret'	, 'Moore'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Dorothy'		, 'Taylor'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Lisa'		, 'Anderson'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Nancy'		, 'Thomas'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Karen'		, 'Jackson'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Betty'		, 'White'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Helen'		, 'Harris'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sandra'		, 'Martin'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Donna'		, 'Thompson'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Carol'		, 'Garcia'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Ruth'		, 'Martinez'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sharon'		, 'Robinson'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Michelle'	, 'Clark'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Laura'		, 'Rodriguez'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sarah'		, 'Lewis'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Kimberly'	, 'Lee'			, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Deborah'		, 'Walker'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Jessica'		, 'Hall'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Shirley'		, 'Allen'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Cynthia'		, 'Young'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Angela'		, 'Hernandez'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Melissa'		, 'King'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Brenda'		, 'Wright'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Amy'			, 'Lopez'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Anna'		, 'Hill'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Rebecca'		, 'Scott'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Virginia'	, 'Green'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Kathleen'	, 'Adams'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Pamela'		, 'Baker'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Martha'		, 'Gonzalez'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Debra'		, 'Nelson'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Amanda'		, 'Carter'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Stephanie'	, 'Mitchell'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Carolyn'		, 'Perez'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Christine'	, 'Roberts'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Marie'		, 'Turner'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Janet'		, 'Phillips'	, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Catherine'	, 'Campbell'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Frances'		, 'Parker'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Ann'			, 'Evans'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Joyce'		, 'Edwards'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Diane'		, 'Collins'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Alice'		, 'Stewart'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Julie'		, 'Sanchez'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Heather'		, 'Morris'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Teresa'		, 'Rogers'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Doris'		, 'Reed'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Gloria'		, 'Cook'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Evelyn'		, 'Morgan'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Jean'		, 'Bell'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Cheryl'		, 'Murphy'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Mildred'		, 'Bailey'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Katherine'	, 'Rivera'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Joan'		, 'Cooper'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Ashley'		, 'Richardson'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Judith'		, 'Cox'			, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Rose'		, 'Howard'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Janice'		, 'Ward'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Kelly'		, 'Torres'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Nicole'		, 'Peterson'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Judy'		, 'Gray'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Christina'	, 'Ramirez'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Kathy'		, 'James'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Theresa'		, 'Watson'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Beverly'		, 'Brooks'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Denise'		, 'Kelly'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Tammy'		, 'Sanders'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Irene'		, 'Price'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Jane'		, 'Bennett'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Lori'		, 'Wood'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Rachel'		, 'Barnes'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Marilyn'		, 'Ross'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Andrea'		, 'Henderson'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Kathryn'		, 'Coleman'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Louise'		, 'Jenkins'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sara'		, 'Perry'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Anne'		, 'Powell'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Jacqueline'	, 'Long'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Wanda'		, 'Patterson'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Bonnie'		, 'Hughes'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Julia'		, 'Flores'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Ruby'		, 'Washington'	, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Lois'		, 'Butler'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Tina'		, 'Simmons'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Phyllis'		, 'Foster'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Norma'		, 'Gonzales'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Paula'		, 'Bryant'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Diana'		, 'Alexander'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Annie'		, 'Russell'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Lillian'		, 'Griffin'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Emily'		, 'Diaz'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Robin'		, 'Hayes'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Peggy'		, 'Myers'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Crystal'		, 'Ford'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Gladys'		, 'Hamilton'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Rita'		, 'Graham'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Dawn'		, 'Sullivan'	, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Connie'		, 'Wallace'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Florence'	, 'Woods'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Tracy'		, 'Cole'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Edna'		, 'West'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Tiffany'		, 'Jordan'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Carmen'		, 'Owens'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Rosa'		, 'Reynolds'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Cindy'		, 'Fisher'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Grace'		, 'Ellis'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Wendy'		, 'Harrison'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Victoria'	, 'Gibson'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Edith'		, 'Mcdonald'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Kim'			, 'Cruz'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sherry'		, 'Marshall'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sylvia'		, 'Ortiz'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Josephine'	, 'Gomez'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Thelma'		, 'Murray'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Shannon'		, 'Freeman'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sheila'		, 'Wells'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Ethel'		, 'Webb'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Ellen'		, 'Simpson'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Elaine'		, 'Stevens'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Marjorie'	, 'Tucker'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Carrie'		, 'Porter'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Charlotte'	, 'Hunter'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Monica'		, 'Hicks'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Esther'		, 'Crawford'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Pauline'		, 'Henry'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Emma'		, 'Boyd'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Juanita'		, 'Mason'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Anita'		, 'Morales'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Rhonda'		, 'Kennedy'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Hazel'		, 'Warren'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Amber'		, 'Dixon'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Eva'			, 'Ramos'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Debbie'		, 'Reyes'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','April'		, 'Burns'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Leslie'		, 'Gordon'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Clara'		, 'Shaw'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Lucille'		, 'Holmes'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Jamie'		, 'Rice'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Joanne'		, 'Robertson'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Eleanor'		, 'Hunt'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Valerie'		, 'Black'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Danielle'	, 'Daniels'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Megan'		, 'Palmer'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Alicia'		, 'Mills'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Suzanne'		, 'Nichols'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Michele'		, 'Grant'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Gail'		, 'Knight'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Bertha'		, 'Ferguson'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Darlene'		, 'Rose'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Veronica'	, 'Stone'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Jill'		, 'Hawkins'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Erin'		, 'Dunn'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Geraldine'	, 'Perkins'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Lauren'		, 'Hudson'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Cathy'		, 'Spencer'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Joann'		, 'Gardner'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Lorraine'	, 'Stephens'	, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Lynn'		, 'Payne'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Sally'		, 'Pierce'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Regina'		, 'Berry'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Erica'		, 'Matthews'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Beatrice'	, 'Arnold'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Dolores'		, 'Wagner'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Bernice'		, 'Willis'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Audrey'		, 'Ray'			, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Yvonne'		, 'Watkins'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Annette'		, 'Olson'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'June'		, 'Carroll'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Samantha'	, 'Duncan'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Marion'		, 'Snyder'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Dana'		, 'Hart'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Stacy'		, 'Cunningham'	, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Ana'			, 'Bradley'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Renee'		, 'Lane'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Ida'			, 'Andrews'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Vivian'		, 'Ruiz'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Roberta'		, 'Harper'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Holly'		, 'Fox'			, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Brittany'	, 'Riley'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Melanie'		, 'Armstrong'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Loretta'		, 'Carpenter'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Yolanda'		, 'Weaver'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Jeanette'	, 'Greene'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Laurie'		, 'Lawrence'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Katie'		, 'Elliott'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Kristen'		, 'Chavez'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Vanessa'		, 'Sims'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Alma'		, 'Austin'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Sue'			, 'Peters'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Miss','Elsie'		, 'Kelley'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Beth'		, 'Franklin'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mrs', 'Jeanne'		, 'Lawson'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','James'			, 'Smith'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','John'			, 'Johnson'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Robert'		, 'Williams'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Michael'		, 'Jones'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','William'		, 'Brown'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','David'			, 'Davis'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Richard'		, 'Miller'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Charles'		, 'Wilson'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Joseph'		, 'Moore'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Thomas'		, 'Taylor'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Christopher'	, 'Anderson'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Daniel'		, 'Thomas'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Paul'			, 'Jackson'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Mark'			, 'White'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Donald'		, 'Harris'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','George'		, 'Martin'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Kenneth'		, 'Thompson'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Steven'		, 'Garcia'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Edward'		, 'Martinez'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Brian'			, 'Robinson'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Ronald'		, 'Clark'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Anthony'		, 'Rodriguez'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Kevin'			, 'Lewis'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Jason'			, 'Lee'			, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Matthew'		, 'Walker'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Gary'			, 'Hall'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Timothy'		, 'Allen'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jose'			, 'Young'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Larry'			, 'Hernandez'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jeffrey'		, 'King'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Frank'			, 'Wright'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Scott'			, 'Lopez'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Eric'			, 'Hill'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Stephen'		, 'Scott'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Andrew'		, 'Green'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Raymond'		, 'Adams'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Gregory'		, 'Baker'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Joshua'		, 'Gonzalez'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jerry'			, 'Nelson'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Dennis'		, 'Carter'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Walter'		, 'Mitchell'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Patrick'		, 'Perez'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Peter'			, 'Roberts'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Harold'		, 'Turner'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Douglas'		, 'Phillips'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Henry'			, 'Campbell'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Carl'			, 'Parker'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Arthur'		, 'Evans'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Ryan'			, 'Edwards'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Roger'			, 'Collins'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Joe'			, 'Stewart'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Juan'			, 'Sanchez'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Jack'			, 'Morris'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Albert'		, 'Rogers'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jonathan'		, 'Reed'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Justin'		, 'Cook'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Terry'			, 'Morgan'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Gerald'		, 'Bell'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Keith'			, 'Murphy'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Samuel'		, 'Bailey'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Willie'		, 'Rivera'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Ralph'			, 'Cooper'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Lawrence'		, 'Richardson'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Nicholas'		, 'Cox'			, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Roy'			, 'Howard'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Benjamin'		, 'Ward'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Bruce'			, 'Torres'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Brandon'		, 'Peterson'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Adam'			, 'Gray'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Harry'			, 'Ramirez'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Fred'			, 'James'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Wayne'			, 'Watson'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Billy'			, 'Brooks'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Steve'			, 'Kelly'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Louis'			, 'Sanders'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jeremy'		, 'Price'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Aaron'			, 'Bennett'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Randy'			, 'Wood'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Howard'		, 'Barnes'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Eugene'		, 'Ross'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Carlos'		, 'Henderson'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Russell'		, 'Coleman'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Bobby'			, 'Jenkins'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Victor'		, 'Perry'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Martin'		, 'Powell'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Ernest'		, 'Long'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Phillip'		, 'Patterson'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Todd'			, 'Hughes'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Jesse'			, 'Flores'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Craig'			, 'Washington'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Alan'			, 'Butler'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Shawn'			, 'Simmons'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Clarence'		, 'Foster'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Sean'			, 'Gonzales'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Philip'		, 'Bryant'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Chris'			, 'Alexander'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Johnny'		, 'Russell'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Earl'			, 'Griffin'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jimmy'			, 'Diaz'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Antonio'		, 'Hayes'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Danny'			, 'Myers'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Bryan'			, 'Ford'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Tony'			, 'Hamilton'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Luis'			, 'Graham'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Mike'			, 'Sullivan'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Stanley'		, 'Wallace'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Leonard'		, 'Woods'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Nathan'		, 'Cole'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Dale'			, 'West'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Manuel'		, 'Jordan'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Rodney'		, 'Owens'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Curtis'		, 'Reynolds'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Norman'		, 'Fisher'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Allen'			, 'Ellis'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Marvin'		, 'Harrison'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Vincent'		, 'Gibson'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Glenn'			, 'Mcdonald'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jeffery'		, 'Cruz'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Travis'		, 'Marshall'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jeff'			, 'Ortiz'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Chad'			, 'Gomez'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Jacob'			, 'Murray'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Lee'			, 'Freeman'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Melvin'		, 'Wells'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Alfred'		, 'Webb'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Kyle'			, 'Simpson'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Francis'		, 'Stevens'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Bradley'		, 'Tucker'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jesus'			, 'Porter'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Herbert'		, 'Hunter'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Frederick'		, 'Hicks'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Ray'			, 'Crawford'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Joel'			, 'Henry'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Edwin'			, 'Boyd'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Don'			, 'Mason'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Eddie'			, 'Morales'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Ricky'			, 'Kennedy'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Troy'			, 'Warren'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Randall'		, 'Dixon'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Barry'			, 'Ramos'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Alexander'		, 'Reyes'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Bernard'		, 'Burns'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Mario'			, 'Gordon'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Leroy'			, 'Shaw'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Francisco'		, 'Holmes'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Marcus'		, 'Rice'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Micheal'		, 'Robertson'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Theodore'		, 'Hunt'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Clifford'		, 'Black'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Miguel'		, 'Daniels'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Oscar'			, 'Palmer'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Jay'			, 'Mills'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jim'			, 'Nichols'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Tom'			, 'Grant'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Calvin'		, 'Knight'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Alex'			, 'Ferguson'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jon'			, 'Rose'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Ronnie'		, 'Stone'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Bill'			, 'Hawkins'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Lloyd'			, 'Dunn'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Tommy'			, 'Perkins'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Leon'			, 'Hudson'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Derek'			, 'Spencer'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Warren'		, 'Gardner'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Darrell'		, 'Stephens'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jerome'		, 'Payne'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Floyd'			, 'Pierce'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Leo'			, 'Berry'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Alvin'			, 'Matthews'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Tim'			, 'Arnold'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Wesley'		, 'Wagner'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Gordon'		, 'Willis'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Dean'			, 'Ray'			, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Greg'			, 'Watkins'		, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Jorge'			, 'Olson'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Dustin'		, 'Carroll'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Pedro'			, 'Duncan'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Derrick'		, 'Snyder'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Dan'			, 'Hart'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Lewis'			, 'Cunningham'	, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Zachary'		, 'Bradley'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Corey'			, 'Lane'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Herman'		, 'Andrews'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Maurice'		, 'Ruiz'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Vernon'		, 'Harper'		, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Roberto'		, 'Fox'			, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Clyde'			, 'Riley'		, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Glen'			, 'Armstrong'	, 4);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Hector'		, 'Carpenter'	, 5);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Shane'			, 'Weaver'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Ricardo'		, 'Greene'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Sam'			, 'Lawrence'	, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Rick'			, 'Elliott'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Lester'		, 'Chavez'		, 1);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Brent'			, 'Sims'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Ms','Ramon'			, 'Austin'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Dr','Charlie'		, 'Peters'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Tyler'			, 'Kelley'		, 2);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Gilbert'		, 'Franklin'	, 3);
INSERT INTO public.customers(customer_id, title, first_name, last_name, type) VALUES (nextval('public.customers_seq'), 'Mr','Gene'			, 'Lawson'		, 3);

CREATE EXTENSION fuzzystrmatch;
GRANT EXECUTE ON FUNCTION metaphone (TEXT, INT) TO PUBLIC;
UPDATE public.customers
SET
  first_name_metaphone = metaphone(first_name, 30),
  last_name_metaphone  = metaphone(last_name, 30),
  modified_when        = current_timestamp - INTERVAL '10 minute' * 100 * random();

COMMIT;